// Four-dimensional solids, and the projection that brings them here.
//
// `grain-shapes.js` holds three shapes called `simplex 5`, `simplex 7` and
// `simplex 9`, and its own comment is honest about what they are: points spread
// by the golden spiral on a sphere with every pair joined, "rather than a
// projection of the real thing". They read well and they are not simplexes.
// The sheet they were taken from — `Reference Docs/Gran Shapes/Projections-of-
// three-dimensional-images-of-multidimensional-right-angle-simplexes.webp` — is
// showing genuine projections, and this file builds those.
//
// **A 4D solid is not a model.** That is the whole difference, and everything
// here follows from it. A tetrahedron has one shape and the room turns it; a
// tesseract's *silhouette in three dimensions* depends on how it is turned in
// four, so its 3D model is an output rather than a thing. Two of its cubes
// swap places as it rotates through the `zw` plane, and no amount of turning it
// in three will do that. So a polytope holds its vertices in R^n and hands out
// a 3D model on demand.
//
// **Rotation in four dimensions happens in a plane, not about an axis.** In
// three, "about the z axis" is really "in the xy plane" — the axis is a
// convenient stand-in that only exists because the orthogonal complement of a
// plane in R³ happens to be a line. In R⁴ that complement is another plane, so
// there is no axis to name and there are six planes rather than three: xy, xz,
// xw, yz, yw, zw. The interface says planes, because that is what they are.
//
// Nothing here touches the DOM. Give it a name, get vertices; give it vertices
// and six angles, get something the room can draw.

/// Vertices closer together than this are the same vertex.
const S4_WELD = 1e-9;

/// How much longer than the shortest edge a pair may be and still be an edge.
///
/// The regular 4-polytopes are all equal-edged, so this is exact in principle.
/// It is a band because the 600-cell's coordinates go through φ and land a
/// rounding error apart — and a band that is too tight silently drops most of a
/// wireframe, which looks like a modelling mistake rather than a tolerance one.
/// The same reasoning, and very nearly the same number, as `GS_EDGE_BAND`.
const S4_EDGE_BAND = 1.02;

const S4_PHI = (1 + Math.sqrt(5)) / 2;

// ── vectors in any number of dimensions ─────────────────────────────────────

const s4Dist = (a, b) => {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += (a[i] - b[i]) ** 2;
  return Math.sqrt(s);
};

/// Centre a set of vertices and scale the furthest to one.
///
/// Same contract as `gsUnit` in `grain-shapes.js`: a grain is placed and sized
/// by the room, so a solid that arrived twice the size of its neighbour would
/// be a grain twice as loud without anything having been said about the sound.
function s4Unit(verts) {
  const d = verts[0].length;
  const c = new Array(d).fill(0);
  for (const v of verts) for (let i = 0; i < d; i++) c[i] += v[i];
  for (let i = 0; i < d; i++) c[i] /= verts.length;
  let r = 0;
  for (const v of verts) r = Math.max(r, s4Dist(v, c));
  const k = r > 0 ? 1 / r : 1;
  return verts.map((v) => v.map((x, i) => (x - c[i]) * k));
}

/// Fold vertices that landed on top of each other into one.
///
/// The 24-cell and the 600-cell are both generated by taking permutations with
/// signs, and both generate some of their vertices more than once.
function s4Weld(verts) {
  const out = [];
  for (const v of verts) {
    if (!out.some((w) => s4Dist(v, w) < S4_WELD)) out.push(v);
  }
  return out;
}

/// Every pair at the shortest distance there is — the edges of an equal-edged
/// solid, without having to write them out.
function s4ShortestEdges(verts) {
  let min = Infinity;
  for (let i = 0; i < verts.length; i++) {
    for (let j = i + 1; j < verts.length; j++) {
      const d = s4Dist(verts[i], verts[j]);
      if (d > S4_WELD && d < min) min = d;
    }
  }
  const cut = min * S4_EDGE_BAND;
  const edges = [];
  for (let i = 0; i < verts.length; i++) {
    for (let j = i + 1; j < verts.length; j++) {
      if (s4Dist(verts[i], verts[j]) <= cut) edges.push([i, j]);
    }
  }
  return edges;
}

// ── the solids ──────────────────────────────────────────────────────────────

/**
 * A regular simplex of `n` dimensions: `n + 1` vertices, every pair joined.
 *
 * The real construction, not a spiral. The `n + 1` basis vectors of R^(n+1) are
 * already a regular simplex — every pair is √2 apart — but they sit in the
 * hyperplane where the coordinates sum to one, which is a slice of a space one
 * dimension too big. So an orthonormal basis is built for that hyperplane and
 * the vertices are re-expressed in it, which is the same solid written in the
 * `n` dimensions it actually occupies.
 *
 * Gram-Schmidt rather than a closed form because it is checkable by eye and
 * general in `n`, and this runs once at load for a handful of solids.
 */
function s4Simplex(n) {
  const m = n + 1;
  // An orthonormal basis of the hyperplane orthogonal to (1, 1, … 1).
  const basis = [];
  for (let k = 0; k < n; k++) {
    // Start from a vector that is not yet in the span: e_k minus its share of
    // the diagonal, which is guaranteed to lie in the hyperplane.
    const v = new Array(m).fill(-1 / m);
    v[k] += 1;
    for (const b of basis) {
      let dot = 0;
      for (let i = 0; i < m; i++) dot += v[i] * b[i];
      for (let i = 0; i < m; i++) v[i] -= dot * b[i];
    }
    let len = 0;
    for (const x of v) len += x * x;
    len = Math.sqrt(len);
    basis.push(v.map((x) => x / len));
  }

  const verts = [];
  for (let i = 0; i < m; i++) {
    const p = [];
    for (let k = 0; k < n; k++) p.push(basis[k][i]);
    verts.push(p);
  }
  // Every pair of a simplex's vertices is joined — that is what a simplex is,
  // and it is why these read as a knot of chords rather than as a cage.
  const edges = [];
  for (let i = 0; i < m; i++) for (let j = i + 1; j < m; j++) edges.push([i, j]);
  return { dim: n, verts: s4Unit(verts), edges };
}

/// The measure polytope of `n` dimensions: every combination of ±1.
///
/// Two vertices are joined when they differ in exactly one coordinate, which is
/// the definition rather than a distance test — for a cube the two happen to
/// agree, and stating the definition means the count is right by construction.
function s4Cube(n) {
  const verts = [];
  for (let i = 0; i < 2 ** n; i++) {
    const v = [];
    for (let k = 0; k < n; k++) v.push((i >> k) & 1 ? 1 : -1);
    verts.push(v);
  }
  const edges = [];
  for (let i = 0; i < verts.length; i++) {
    for (let j = i + 1; j < verts.length; j++) {
      let differ = 0;
      for (let k = 0; k < n; k++) if (verts[i][k] !== verts[j][k]) differ++;
      if (differ === 1) edges.push([i, j]);
    }
  }
  return { dim: n, verts: s4Unit(verts), edges };
}

/// The cross polytope of `n` dimensions: ±1 on one axis, zero on the rest.
///
/// In four dimensions this is the 16-cell, the tesseract's dual. Every pair is
/// joined except the two that are opposite along an axis, so it is a simplex
/// with its long diagonals missing.
function s4Cross(n) {
  const verts = [];
  for (let k = 0; k < n; k++) {
    for (const s of [1, -1]) {
      const v = new Array(n).fill(0);
      v[k] = s;
      verts.push(v);
    }
  }
  return { dim: n, verts: s4Unit(verts), edges: s4ShortestEdges(s4Unit(verts)) };
}

/// The 24-cell: every permutation of (±1, ±1, 0, 0).
///
/// The one regular 4-polytope with no analogue in any other dimension — it is
/// its own dual, and nothing in three or five dimensions is like it. Twenty-four
/// vertices, ninety-six edges.
function s4Cell24() {
  const verts = [];
  for (let a = 0; a < 4; a++) {
    for (let b = a + 1; b < 4; b++) {
      for (const sa of [1, -1]) {
        for (const sb of [1, -1]) {
          const v = [0, 0, 0, 0];
          v[a] = sa; v[b] = sb;
          verts.push(v);
        }
      }
    }
  }
  const welded = s4Unit(s4Weld(verts));
  return { dim: 4, verts: welded, edges: s4ShortestEdges(welded) };
}

/// Every even permutation of a four-element pattern.
///
/// A permutation is even when it takes an even number of swaps to build. The
/// 600-cell needs exactly these — the odd ones give its mirror image, and
/// including both would give 192 vertices of something that is not a 600-cell.
function s4EvenPerms(pattern) {
  const out = [];
  const idx = [0, 1, 2, 3];
  const permute = (arr, k, swaps) => {
    if (k === arr.length) {
      if (swaps % 2 === 0) out.push(arr.map((i) => pattern[i]));
      return;
    }
    for (let i = k; i < arr.length; i++) {
      const next = arr.slice();
      next[k] = arr[i]; next[i] = arr[k];
      permute(next, k + 1, swaps + (i === k ? 0 : 1));
    }
  };
  permute(idx, 0, 0);
  return out;
}

/**
 * The 600-cell: 120 vertices, 720 edges.
 *
 * Three families, which is the standard construction: the 16-cell's eight, the
 * tesseract's sixteen at half scale, and ninety-six from the even permutations
 * of (±φ/2, ±½, ±1/2φ, 0). The golden ratio is what makes this one work, and it
 * is why the edge band above cannot be an equality test.
 */
function s4Cell600() {
  const verts = [];
  // The 16-cell.
  for (let k = 0; k < 4; k++) {
    for (const s of [1, -1]) {
      const v = [0, 0, 0, 0];
      v[k] = s;
      verts.push(v);
    }
  }
  // The tesseract, at half.
  for (let i = 0; i < 16; i++) {
    verts.push([0, 1, 2, 3].map((k) => (((i >> k) & 1) ? 0.5 : -0.5)));
  }
  // And the ninety-six.
  const a = S4_PHI / 2, b = 0.5, c = 1 / (2 * S4_PHI);
  for (const sa of [1, -1]) {
    for (const sb of [1, -1]) {
      for (const sc of [1, -1]) {
        for (const p of s4EvenPerms([sa * a, sb * b, sc * c, 0])) verts.push(p);
      }
    }
  }
  const welded = s4Unit(s4Weld(verts));
  return { dim: 4, verts: welded, edges: s4ShortestEdges(welded) };
}

// ── turning one ─────────────────────────────────────────────────────────────

/// The six planes of rotation in four dimensions, in the order the panel shows
/// them: the three that are also rotations in three dimensions, then the three
/// that reach into the fourth.
///
/// `xy` turns x into y and leaves z and w alone — which in three dimensions
/// would be called a rotation about z. The last three have no such name, and
/// they are the ones that do something you cannot otherwise see.
const S4_PLANES = [
  { key: 'xy', label: 'XY', a: 0, b: 1, familiar: true },
  { key: 'xz', label: 'XZ', a: 0, b: 2, familiar: true },
  { key: 'yz', label: 'YZ', a: 1, b: 2, familiar: true },
  { key: 'xw', label: 'XW', a: 0, b: 3, familiar: false },
  { key: 'yw', label: 'YW', a: 1, b: 3, familiar: false },
  { key: 'zw', label: 'ZW', a: 2, b: 3, familiar: false },
];

/// Turn a set of vertices through the six planes, in the order above.
///
/// Rotations in four dimensions do not commute any more than they do in three,
/// so the order is part of the answer and is fixed here rather than left to
/// whoever calls it. Angles are radians, keyed by plane.
function s4Rotate(verts, angles) {
  let out = verts;
  for (const p of S4_PLANES) {
    const t = angles?.[p.key] || 0;
    if (!t) continue;
    const c = Math.cos(t), s = Math.sin(t);
    out = out.map((v) => {
      const next = v.slice();
      next[p.a] = v[p.a] * c - v[p.b] * s;
      next[p.b] = v[p.a] * s + v[p.b] * c;
      return next;
    });
  }
  return out;
}

/**
 * Bring `dim` dimensions down to three.
 *
 * Perspective is the one worth having and the reason these look alive: a vertex
 * further away in w is drawn smaller, so the inner cube of a tesseract is the
 * far one rather than a smaller cube inside a bigger one. Turning it in `zw`
 * then swings the two through each other, which is the thing you cannot show
 * any other way.
 *
 * `eye` is how far down the w axis the viewer stands. Large is nearly
 * orthographic; approaching the solid's own radius it blows up, so it is held
 * clear of the vertices rather than allowed to divide by zero.
 *
 * Anything above four dimensions is dropped one at a time by the same rule, so
 * a 9-simplex arrives through six perspective divisions — which is what the
 * projection sheets show and why those look like knots rather than cages.
 */
function s4Project(verts, { eye = 2.5, mode = 'perspective' } = {}) {
  let out = verts;
  while (out[0].length > 3) {
    const d = out[0].length - 1;
    if (mode === 'orthographic') {
      out = out.map((v) => v.slice(0, d));
      continue;
    }
    // Never divide by nothing: the eye is pushed past the furthest vertex on
    // this axis if it has been asked to stand inside the solid.
    let far = 0;
    for (const v of out) far = Math.max(far, v[d]);
    const e = Math.max(eye, far + 0.05);
    out = out.map((v) => {
      const k = e / (e - v[d]);
      return v.slice(0, d).map((x) => x * k);
    });
  }
  return out;
}

/**
 * A polytope, turned and projected, in the shape `vis-gl` already draws.
 *
 * Deliberately the same `{ pos, idx }` a `grain-shapes.js` model carries, so a
 * four-dimensional solid is drawable everywhere a three-dimensional one is and
 * nothing downstream has to know the difference. No skin: every one of these is
 * a wireframe, for the reason that file gives — one light, additive blending,
 * and a filled face under that is a bright patch with no form in it.
 */
function s4Model(shape, angles, projection) {
  const turned = s4Rotate(shape.verts, angles);
  const flat = s4Project(turned, projection);
  // Re-centred and re-scaled *after* projecting, because perspective changes
  // the size: without this a tesseract pulses as it turns, which reads as the
  // grain getting louder.
  const unit = s4Unit(flat);
  const pos = new Float32Array(unit.length * 3);
  for (let i = 0; i < unit.length; i++) {
    pos[i * 3] = unit[i][0]; pos[i * 3 + 1] = unit[i][1]; pos[i * 3 + 2] = unit[i][2];
  }
  const idx = new Uint16Array(shape.edges.length * 2);
  for (let i = 0; i < shape.edges.length; i++) {
    idx[i * 2] = shape.edges[i][0]; idx[i * 2 + 1] = shape.edges[i][1];
  }
  return { pos, idx, verts: unit.length, lines: shape.edges.length };
}

// ── the catalogue ───────────────────────────────────────────────────────────

/// Every four-dimensional solid this program builds, with what it should have.
///
/// `verts` and `edges` are stated rather than measured, and the tests check the
/// built solid against them. A construction that quietly produces 191 vertices
/// of something that is not a 600-cell is otherwise indistinguishable from one
/// that works — it still draws, and it still looks like a knot.
///
/// The 120-cell is **not here**, and is not faked. It is the sixth regular
/// 4-polytope, 600 vertices and 1200 edges, and building it properly means
/// deriving it as the 600-cell's dual. Listing an entry that draws something
/// else under its name is the thing this file exists to stop doing.
const SHAPES_4D = [
  { key: 'cell5', label: '5-cell', dim: 4, verts: 5, edges: 10,
    hint: 'The simplex of four dimensions — five vertices, every pair joined. The tetrahedron’s next of kin.',
    build: () => s4Simplex(4) },
  { key: 'cell8', label: '8-cell · tesseract', dim: 4, verts: 16, edges: 32,
    hint: 'The hypercube. Eight cubic cells; in perspective one sits inside another, and a turn through ZW swings them through each other.',
    build: () => s4Cube(4) },
  { key: 'cell16', label: '16-cell', dim: 4, verts: 8, edges: 24,
    hint: 'The tesseract’s dual, and the four-dimensional octahedron. Every pair joined but the opposite ones.',
    build: () => s4Cross(4) },
  { key: 'cell24', label: '24-cell', dim: 4, verts: 24, edges: 96,
    hint: 'Its own dual, and the one regular solid with no analogue in any other dimension. Nothing in three dimensions is like it.',
    build: s4Cell24 },
  { key: 'cell600', label: '600-cell', dim: 4, verts: 120, edges: 720,
    hint: 'Six hundred tetrahedral cells. The densest of them, and the one that most reads as a shell of chords.',
    build: s4Cell600 },
  { key: 'simplex5', label: 'Simplex · 5D', dim: 5, verts: 6, edges: 15,
    hint: 'A regular simplex of five dimensions, brought down through two perspective divisions.',
    build: () => s4Simplex(5) },
  { key: 'simplex7', label: 'Simplex · 7D', dim: 7, verts: 8, edges: 28,
    hint: 'Seven dimensions, four divisions. The chording the projection sheets are showing.',
    build: () => s4Simplex(7) },
  { key: 'simplex9', label: 'Simplex · 9D', dim: 9, verts: 10, edges: 45,
    hint: 'Nine dimensions, six divisions — the densest knot the sheets carry.',
    build: () => s4Simplex(9) },
];

/// Built once, on first ask. A solid nobody looks at costs nothing, and the
/// 600-cell is 120 vertices compared pairwise, which is not free.
const s4Built = new Map();

function s4Shape(key) {
  if (!s4Built.has(key)) {
    const entry = SHAPES_4D.find((s) => s.key === key);
    s4Built.set(key, entry ? entry.build() : null);
  }
  return s4Built.get(key);
}

function s4Entry(key) {
  return SHAPES_4D.find((s) => s.key === key) || null;
}

const Shapes4D = {
  PLANES: S4_PLANES,
  CATALOGUE: SHAPES_4D,
  shape: s4Shape,
  entry: s4Entry,
  model: s4Model,
  rotate: s4Rotate,
  project: s4Project,
  simplex: s4Simplex,
  cube: s4Cube,
  cross: s4Cross,
};
